services:
  postgres:
    image: postgres:15-alpine
    container_name: shopify-mock-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopify_mock
    ports:
      - "5511:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: node:20-alpine
    container_name: shopify-mock-app
    working_dir: /app
    command: sh -c "./node_modules/.bin/ts-node src/main.ts"
    environment:
      NODE_ENV: development
      PORT: 3111
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: shopify_mock
    ports:
      - "3111:3111"
    volumes:
      - .:/app
    depends_on:
      - postgres

volumes:
  postgres_data:
